config/routes.rb
LandingpageJs::Application.routes.draw do
  resources :page_elements

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :landing_pages do
    resources :page_elements
    member do 
      post :duplicate
    end
  end

  root :to => 'landing_pages#index'
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/landing_page.rb
class LandingPage < ActiveRecord::Base
  attr_accessible :json, :description, :title
  has_many :page_elements
 


  def to_param

    "#{id}-#{title.parameterize}"
    
  end


 
end

app/models/page_element.rb
class PageElement < ActiveRecord::Base
  belongs_to :landing_page
  attr_accessible :label, :value, :landing_page_id

  validate :label, :present => true

  def to_json

    {"#{label}" => "#{value}"}
    
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController

  def show

    # data = {:headline => "Apple Pie", :subhead => "3.75"}
    

    respond_to do |format|
      format.html {
        @landing_page = LandingPage.find params[:id]
        
      }
      format.json {
        if params[:id] == "default"
          page = LandingPage.first
        else
          page = LandingPage.find(params[:id])
        end
        if page
          elements = Hash.new

          page.page_elements.each do |element|
            elements.merge! element.to_json
          end

          data = elements
        else
          data = {}
        end
        render :json => data, :callback => params[:callback]

      }
  end   
    


  end


  def new
    @landing_page = LandingPage.new
  end

  def duplicate

    original = LandingPage.find params[:id]

    copy = LandingPage.create :title => "#{original.title} - Copy", :description => "#{original.description}"
    
    original.page_elements.each do |page_element|
      copy.page_elements.create :label => page_element.label, :value => page_element.value
    end

    redirect_to landing_pages_path
    
  end

  def index

    @landinge_pages = LandingPage.all
    
  end


  def create

    @landing_page = LandingPage.new params[:landing_page]

    if @landing_page.save
      redirect_to landing_pages_path
    else
      render :new
    end
  end

  def edit
    @landing_page = LandingPage.find params[:id]
    
  end

  def update

    @landing_page = LandingPage.find params[:id]

    if @landing_page.update_attributes params[:landing_page]
      redirect_to landing_pages_path
    else
      render :edit
    end
  end

  def destroy

    @landing_page = LandingPage.find params[:id]
    @landing_page.destroy

    redirect_to landing_pages_path
  end


end

app/controllers/page_elements_controller.rb
class PageElementsController < ApplicationController

  before_filter :load_landing_page
  def new
    @page_element = @landing_page.page_elements.new
  end

  def create


    @element = @landing_page.page_elements.new params[:page_element]
    if @element.save
      redirect_to landing_page_path(@landing_page)
    else
      render :new
    end
  end

  def update

    @page_element = @landing_page.page_elements.find params[:id]

 
    respond_to do |format|
      format.html {
        if @page_element.update_attributes params[:page_element]
          redirect_to landing_page_path(@landing_page)
        else
          render :edit
        end


      }
      format.js {
        if @page_element.update_attributes params[:page_element]
          render :text => "alert('updated')"
        else
          render :text => "alert('failed')"
      end

      }
    end
  end

  def edit

    @page_element = @landing_page.page_elements.find params[:id]

  end

  def destroy
    if ( @landing_page.page_elements.exists? params[:id])
      @page_element = @landing_page.page_elements.find params[:id]      
      @page_element.destroy
    else
      flash[:notice]  = "Could not find the element to delete"
    end
    redirect_to landing_page_path(@landing_page)
  
  end

  protected

  def load_landing_page

    @landing_page = LandingPage.find params[:landing_page_id]
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/page_elements_helper.rb
module PageElementsHelper
end

app/views/landing_pages/edit.html.haml
= form_for @landing_page do |f|
  = f.label :title
  = f.text_field :title
  = f.label :description
  = f.text_area :description
  .actions
    = f.submit

app/views/landing_pages/index.html.haml
- content_for :actions do
  =link_to "New Landing Page", new_landing_page_path

%table.table
  %tr
    %th Landing Page
    %th Code
    %th
  - @landinge_pages.each do |landing_page|
    %tr
      %td
        #landing_page= link_to landing_page.title, landing_page_path(landing_page)
      %td= landing_page.to_param
      %td
        .controls
          = link_to "Edit", edit_landing_page_path(landing_page)
          = link_to "Destroy", landing_page_path(landing_page), :method => :delete, :confirm => "Are you sure you want to delete this landing page?"
          = link_to "Duplicate", duplicate_landing_page_path(landing_page), :method => :post

app/views/landing_pages/new.html.haml
= form_for @landing_page do |f|
  = f.label :title
  = f.text_field :title
  = f.label :description
  = f.text_field :description
  .actions
    = f.submit

app/views/landing_pages/show.html.haml
- content_for :actions do 
  #add_element= link_to "Add Element", new_landing_page_page_element_path( @landing_page ), :class => :button
- content_for :title, @landing_page.title

#description= @landing_page.description
#page_elements
  %table.table
    %tr
      %th Label
      %th Value
      %th
    
    - @landing_page.page_elements.each do |element|
      %tr
        %td#label= element.label
        %td#value
          = form_for element, :url => landing_page_page_element_path(@landing_page, element), :remote => true do |f|
            = f.text_area :value
            = f.submit
        %td.controls
          
          .delete= link_to "Destroy", landing_page_page_element_path(@landing_page, element), :method => :delete

app/views/layouts/_messages.html.haml
= flash[:notice]

app/views/layouts/_navigation.html.haml
= link_to "Home", root_path, :class => 'brand'
%ul.nav

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Myapp"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          =  render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              =  render 'layouts/messages'
          
              #actions= yield :actions
          
              %h1= yield :title
              
          .row= yield
          %footer

app/views/page_elements/edit.html.haml
= form_for @page_element, :url => landing_page_page_element_path(@landing_page, @page_element) do |f|
  = f.label :label
  = f.text_field :label
  = f.label :value
  = f.text_field :value
  = f.submit

app/views/page_elements/new.html.haml
= form_for @page_element, :url => landing_page_page_elements_path(@landing_page) do |f|
  = f.label :label
  = f.text_field :label
  = f.label :value
  = f.text_field :value
  = f.submit